import Head from "next/head";
import Footer from "../components/Footer";
import Header from "../components/Header";
// Components
import SpliceBall from "../components/SplineBall";

import * as Style from "../styles/style";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Style.Main>
        <section className="text">
          <h1 translate="no">Ingrante <strong>3D</strong> to Webflow</h1>
          <p translate="no">
          Practicing 3D Modeling with Spline . Lorem ipsum dolor sit amet consectetur adipisicing elit. Impedit nemo, quod earum
          </p>
        </section>
        <div>
          <SpliceBall />
        </div>
      </Style.Main>
      <Footer />
    </>
  );
}
